### PR TITLE
Order independent array diff

### PR DESCRIPTION
**Pull request by jsfuchs**

### CODE REVIEW

**Comment by jsfuchs** [comment]
Whoops - didn't mean to open it against your repo (wanted to put it into my forked master :D)

**Comment by NewOldMax** [comment]
It's very useful feature. Can this be in main package?

**Comment by jsfuchs** [comment]
Sure!

**Comment by jsfuchs** [comment]
Ah ok I'll work on the conflicts on Monday.

**Comment by NewOldMax** [comment]
@jsfuchs 
this can solve #100 , right?

**Comment by jsfuchs** [comment]
So yes and no - 

It will be able to determine if there is a difference between two unordered objects/arrays, but the output of the diff is particularly smart or useful since the sorting doesn't always align "like" terms. There would probably have to be a fair amount of work to make the output a sensible diff.

**Comment by flitbit** [comment]
I'm checking it out; if it does what it says, I agree.

**Comment by jsfuchs** [comment]
Wrong branch - I'll reopen

**Comment by nk1g13** [comment]
Would be very useful to have this feature, exactly facing the case #100 .

**Pull request closed without merging**
