### PR TITLE
passing the actual object to the prefilter

### PR DESCRIPTION
**Pull request by Orlando80**
the name of the key is not enough in my project. I need to have more info to take a decision whether to filter or not.

### CODE REVIEW

**Comment by DavidTPate** [comment]
Why can't you just access your LHS and RHS in your code?

**Comment by Orlando80** [comment]
Maybe I missed something but this is an example, can you tell me how do I access lhs and rhs? 

diff(x, y,function(path, key) {
           // return true if lhs and rhs are both dates without checking the value
            })

**Comment by DavidTPate** [comment]
You wouldn't be accessing them from the diff function. If we were to expand the example some, let's say we have:

```js
var x = {
  a: 1
};
var b = {
  a: 2
};

diff(x, y, function(path, key) {
 // At this point both x and y are accessible due to the scoping of the callback.
});
```

As you can see both `x` and `y` are accessible within the scope due to closure. So in Javascript a function created in another function has access to the parent function's scope. This is why the library doesn't need to pass the LHS and RHS back, since in order to call the function in the first place you already have access to those variables.

**Comment by Orlando80** [comment]
That's not the point.
x and y are not lhs and rhs. let's have a more complex example:
var x = { a: { b: 1} }
var y = { a: { b: 2} }

the filter function return me a key called 'b' (a string)
I need to check that b is a Date
I can access x and y, but I don't know where b is, inside x and y.
lhs and rhs are the actual objects I need to check.
And also if you can find it out somehow in this case, I can go on with more complex objects.

**Comment by Orlando80** [comment]
@flitbit can you please have a look at this? I'm going to use your module in my testing suite if you merge this.

**Comment by flitbit** [comment]
Makes total sense to me. Thank you

**Comment by flitbit** [comment]
Published 0.3.2 on npm

**Pull request merged**
